#!/bin/sh

[ -f "/etc/config/ucitrack" ] && {
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ddnstox[-1]
	add ucitrack ddnstox
	set ucitrack.@ddnstox[-1].init=ddnstox
	commit ucitrack
EOF
}

/etc/init.d/ddnstox enable

rm -rf /tmp/luci-*
exit 0
