# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-ddnstox
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

PKG_MAINTAINER:=sbwml <admin@cooluc.com>

LUCI_TITLE:=LuCI support for ddnsto-custom
LUCI_DEPENDS:=+ddnstox

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
